# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: kbatch.k8s.io/v1beta1
kind: BatchJob
metadata:
  name:  $jobName
  namespace: $namespace
  labels:
    $jobCategoryLabelName: data-util
spec:
  batchQueueName: $queue
  taskGroups:
    - name: $groupName
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: data-util
              image: tobereplaced
              resources: {}
              volumeMounts:
                - name: data-volume
                  mountPath: $mountPath
          volumes:
            - name: data-volume
              persistentVolumeClaim:
                claimName: $pvc
                readOnly: false