apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: kbatch-gcs-example-role
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  resourceNames: ["kbatch-gcs-example-k8s-sa"]
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kbatch-gcs-example-rb
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kbatch-gcs-example-role
subjects:
- kind: User
  apiGroup: rbac.authorization.k8s.io
  name: [your_alias]@[your_domain].com