apiVersion: kbatch.k8s.io/v1beta1
kind: BatchJob
metadata:
  generateName: array-image-
  namespace: default
spec:
  batchQueueName: default
  taskGroups:
  - name: main
    maxWallTime: 10m
    indexSpec:
      taskCount: 5
    template:
      spec:
        containers:
          - name: greyimage
            # This image has been made public so it can be pulled from any project.
            image: gcr.io/kbatch-images/greyimage/greyimage:latest
            command: ["./greyimage"]
            args: ["-in=/mnt/pv/array-image-data/input_$(KBATCH_ARRAY_INDEX).png", "-out=/mnt/pv/array-image-data/output_$(KBATCH_ARRAY_INDEX).png"]
            volumeMounts:
              - mountPath: /mnt/pv
                name: mypvc
            resources:
              limits:
                cpu: 1.0
                memory: 2Gi
              requests:
                cpu: 1.0
                memory: 2Gi
            imagePullPolicy: IfNotPresent
        restartPolicy: Never
        volumes:
          - name: mypvc
            persistentVolumeClaim:
              claimName: pvc
              readOnly: false